INSERT INTO tag (id, tag_category_id, tag_value, label, display_order, is_active, created_at, updated_at) VALUES
(101, 1, 'moisturizing_high', '촉촉함이 오래가요', 101, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(102, 1, 'moisturizing_medium', '무난해요', 102, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(103, 1, 'moisturizing_low', '건조함이 느껴져요', 103, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(104, 2, 'refreshing_high', '산뜻해요', 104, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(105, 2, 'refreshing_medium', '무난해요', 105, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(106, 2, 'refreshing_low', '무겁고 끈적여요', 106, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(107, 3, 'fast_absorption', '빠르게 흡수돼요', 107, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(108, 3, 'moderate_absorption', '무난해요', 108, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(109, 3, 'slow_absorption', '흡수가 느려요', 109, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(110, 4, 'soothing_good', '피부 진정에 좋아요', 110, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(111, 4, 'soothing_neutral', '무난해요', 111, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(112, 4, 'soothing_bad', '진정 효과가 없어요', 112, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(113, 5, 'non_irritating', '자극 없이 순해요', 113, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(114, 5, 'mildly_irritating', '무난해요', 114, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(115, 5, 'highly_irritating', '자극적이에요', 115, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(116, 6, 'cleansing_strong', '세정력이 뛰어나요', 116, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(117, 6, 'cleansing_medium', '보통이에요', 117, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(118, 6, 'cleansing_weak', '세정력이 약해요', 118, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(119, 7, 'residue_none', '잔여감이 없어요', 119, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(120, 7, 'residue_some', '잔여감이 조금 있어', 120, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(121, 7, 'residue_heavy', '잔여감이 심해요', 121, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(122, 8, 'uv_protection_high', '차단력이 강해요', 122, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(123, 8, 'uv_protection_medium', '무난해', 123, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(124, 8, 'uv_protection_low', '차단이 약해요', 124, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(125, 9, 'long_lasting', '오래 유지돼요', 125, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(126, 9, 'medium_lasting', '무난해요', 126, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(127, 9, 'short_lasting', '금방 사라져요', 127, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(128, 10, 'vivid_color', '발색력이 좋아요', 128, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(129, 10, 'moderate_color', '무난해', 129, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(130, 10, 'dull_color', '발색이 약해요', 130, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(131, 11, 'smooth_application', '부드럽게 발려요', 131, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(132, 11, 'normal_application', '무난해요', 132, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(133, 11, 'rough_application', '뻑뻑해요', 133, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(134, 12, 'scent_long', '향이 오래가요', 134, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(135, 12, 'scent_medium', '무난해요', 135, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(136, 12, 'scent_short', '향이 금방 사라져요', 136, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(137, 13, 'scent_strong', '향이 진해요', 137, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(138, 13, 'scent_moderate', '향이 은은해요', 138, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(139, 13, 'scent_weak', '향이 약해요', 139, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(140, 14, 'scalp_soothing_good', '두피 진정에 좋아요', 140, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(141, 14, 'scalp_soothing_neutral', '자극 없이 무난해요', 141, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(142, 14, 'scalp_soothing_bad', '두피가 자극 받아요', 142, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(143, 15, 'hair_shiny', '머릿결이 반짝여요', 143, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(144, 15, 'hair_normal', '무난해요', 144, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(145, 15, 'hair_dull', '푸석해 보여요', 145, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(146, 16, 'damage_repair_good', '손상 케어에 좋아요', 146, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(147, 16, 'damage_repair_normal', '무난해요', 147, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(148, 16, 'damage_repair_bad', '효과가 없어요', 148, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(149, 17, 'hair_removal_strong', '제모력이 뛰어나요', 149, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(150, 17, 'hair_removal_normal', '무난해요', 150, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(151, 17, 'hair_removal_weak', '제모력이 약해요', 151, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(152, 18, 'easy_to_use', '사용하기 편해요', 152, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(153, 18, 'normal_use', '무난해요', 153, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(154, 18, 'hard_to_use', '사용하기 어려워요', 154, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(155, 19, 'cost_effective', '가성비 좋아요', 155, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(156, 19, 'average_value', '무난해요', 156, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(157, 19, 'expensive', '비싸요', 157, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(158, 20, 'safe_for_sensitive', '민감 피부도 괜찮아요', 158, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(159, 20, 'safe_normal', '무난해요', 159, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
(160, 20, 'unsafe', '피부에 자극적이에요', 160, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
