server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /var/lib/promtail/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push
    timeout: 30s

scrape_configs:
  - job_name: ururu-backend
    static_configs:
      - targets:
          - localhost
        labels:
          job: ururu-backend
          __path__: /app/logs/ururu-backend.log
    pipeline_stages:
      - json:
          expressions:
            timestamp: timestamp
            level: level
            message: message
            logger: logger
            thread: thread
      - timestamp:
          source: timestamp
          format: RFC3339Nano
      - labels:
          level:
          logger:
          thread: