version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: ururu-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - ururu-blue
      - ururu-green

  ururu-blue:
    image: juwon0909/ururu:blue
    container_name: ururu-blue
    restart: unless-stopped
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env

  ururu-green:
    image: juwon0909/ururu:green
    container_name: ururu-green
    restart: unless-stopped
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env
