version: "3.8"

services:
  springboot-app:
    image: juwon0909/ururu:latest
    container_name: ururu
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - MESSAGE=${MESSAGE}
