version: "3.8"

services:
  nginx:
    image: nginx:latest
    container_name: ururu-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - springboot-app

  springboot-app:
    image: juwon0909/ururu:latest
    container_name: ururu
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    env_file:
      - .env
