auth_enabled: true

server:
  http_listen_port: 3100
  grpc_listen_port: 9096

authn:
  - name: basic_auth
    config:
      basic_auth:
        username: ${LOKI_USERNAME}
        password: ${LOKI_PASSWORD}

authz:
  - name: basic_auth
    config:
      basic_auth:
        username: ${LOKI_USERNAME}
        password: ${LOKI_PASSWORD}

ingester:
  lifecycler:
    address: 127.0.0.1
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
    finalize_ring: false
  chunk_idle_period: 5m
  chunk_retain_period: 1h
  max_chunk_age: 1h

schema_config:
  configs:
    - from: 2020-05-15
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/boltdb-shipper-active
    cache_location: /loki/boltdb-shipper-cache
    cache_ttl: 24h
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks

compactor:
  working_directory: /loki/compactor
  shared_store: filesystem

limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  max_cache_freshness_per_query: 1m
  max_query_length: 721h
  max_query_parallelism: 32
  cardinality_limit: 100000
  max_streams_per_user: 0
  max_global_streams_per_user: 0
  ingestion_rate_mb: 4
  ingestion_burst_size_mb: 6

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: true
  retention_period: 168h  # 7일 보존

query_range:
  align_queries_with_step: true
  max_retries: 5
  split_queries_by_interval: 15m
  cache_results: true
  results_cache:
    cache:
      enable_fifocache: true
      fifocache:
        max_size_bytes: 500MB
        validity: 24h