name: CI/CD - DockerHub Push & EC2 Deploy

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout app repository
        uses: actions/checkout@v3

      - name: Checkout private config repository
        uses: actions/checkout@v3
        with:
          repository: UruruLab/Ururu-Backend-Config
          token: ${{ secrets.PRIVATE_REPO_TOKEN }}
          path: config

      - name: Copy config files (application*.yml and .env)
        run: |
          mkdir -p src/main/resources/
          cp config/application-*.yml src/main/resources/
          cp config/.env .

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant permission to Gradle
        run: chmod +x ./gradlew

      - name: Build Spring Boot JAR
        run: ./gradlew clean bootJar --no-daemon

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      - name: Build Docker image
        run: docker build -t juwon0909/ururu:latest -f docker/Dockerfile .

      - name: Push image to DockerHub
        run: docker push juwon0909/ururu:latest

      - name: Setup SSH for EC2
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa

      - name: Upload docker-compose-prod.yml to EC2
        run: |
          scp -o StrictHostKeyChecking=no docker/docker-compose-prod.yml ${{ secrets.EC2_USER_HOST }}:/home/ec2-user/app/docker-compose.yml

      - name: Deploy on EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER_HOST }} << 'EOF'
            cd /home/ec2-user/app
            docker compose pull
            docker compose down || true
            docker compose up -d
          EOF
